-- Backup de definiciones actuales antes de migrar a asignaciones.id_negocio = 1
-- Fecha: Wed May  6 09:59:11     2026

-- ========== view_asignaciones_saldo_pendiente_corregida ==========
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_asignaciones_saldo_pendiente_corregida` AS select `asignaciones`.`nro_unidad` AS `NroUn.`,`meses`.`mes` AS `Mes`,`asignaciones`.`año` AS `Año`,`grupos`.`grupo` AS `Modelo`,`modelos`.`modelo` AS `Versión`,`asignaciones`.`nro_orden` AS `NroOrden`,`asignaciones`.`interno` AS `Interno`,`asignaciones`.`chasis` AS `Chasis`,`asignaciones`.`cliente` AS `Cliente`,`usuarios`.`nombre` AS `Asesor`,`sucursales`.`sucursal` AS `Sucursal`,`asignaciones`.`fec_reserva` AS `Reserva`,`asignaciones`.`fec_arribo` AS `Arribo`,`asignaciones`.`fec_despacho` AS `Despacho`,`asignaciones`.`estado_tasa` AS `Confirmada TASA`,`asignaciones`.`cancelada` AS `Cancelada`,`asignaciones`.`pagado` AS `pagado_tasa`,`modelos`.`costo` AS `Costo TASA`,`reservas_suma_montos`.`monto` AS `Operacion`,`reservas_suma_pagos`.`pagos` AS `Pagos`,(coalesce(`reservas_suma_montos`.`monto`,0) - coalesce(`reservas_suma_pagos`.`pagos`,0)) AS `Saldo`,`sucursales`.`idsucursal` AS `idsucursal`,`asignaciones`.`estado_reserva` AS `EstadoReserva` from (((((((`asignaciones` join `grupos` on((`asignaciones`.`id_grupo` = `grupos`.`idgrupo`))) join `modelos` on((`asignaciones`.`id_modelo` = `modelos`.`idmodelo`))) join `usuarios` on((`asignaciones`.`id_asesor` = `usuarios`.`idusuario`))) join `meses` on((`asignaciones`.`id_mes` = `meses`.`idmes`))) left join `reservas_suma_montos` on((`asignaciones`.`nro_unidad` = `reservas_suma_montos`.`nrounidad`))) left join `reservas_suma_pagos` on((`asignaciones`.`nro_unidad` = `reservas_suma_pagos`.`nrounidad`))) join `sucursales` on((`usuarios`.`idsucursal` = `sucursales`.`idsucursal`))) where ((`asignaciones`.`guardado` = 1) and (`asignaciones`.`borrar` = 0) and (`asignaciones`.`entregada` = 0) and (`usuarios`.`id_negocio` = 1) and (`asignaciones`.`estado_tasa` = 1) and (not((`asignaciones`.`nro_orden` like 'TPA%'))) and ((`asignaciones`.`año` < year(curdate())) or ((`asignaciones`.`año` = year(curdate())) and (`asignaciones`.`id_mes` <= month(curdate()))))) order by `asignaciones`.`año`,`asignaciones`.`id_mes`;

-- ========== view_asignaciones_saldo_pendiente_corregida_no_llegadas ==========
CREATE ALGORITHM=UNDEFINED DEFINER=`usernavicat`@`%` SQL SECURITY DEFINER VIEW `view_asignaciones_saldo_pendiente_corregida_no_llegadas` AS select `sucursales`.`idsucursal` AS `IdSucursal`,`sucursales`.`sucursal` AS `Sucursal`,sum((coalesce(`reservas_suma_montos`.`monto`,0) - coalesce(`reservas_suma_pagos`.`pagos`,0))) AS `Saldo` from ((((`asignaciones` join `usuarios` on((`asignaciones`.`id_asesor` = `usuarios`.`idusuario`))) join `sucursales` on((`usuarios`.`idsucursal` = `sucursales`.`idsucursal`))) left join `reservas_suma_montos` on((`asignaciones`.`nro_unidad` = `reservas_suma_montos`.`nrounidad`))) left join `reservas_suma_pagos` on((`asignaciones`.`nro_unidad` = `reservas_suma_pagos`.`nrounidad`))) where ((`asignaciones`.`guardado` = 1) and (`asignaciones`.`borrar` = 0) and (`asignaciones`.`entregada` = 0) and (`usuarios`.`id_negocio` = 1) and (`asignaciones`.`estado_tasa` = 1) and (`asignaciones`.`pagado` = 0) and (not((`asignaciones`.`nro_orden` like 'TPA%'))) and ((`asignaciones`.`año` < year(curdate())) or ((`asignaciones`.`año` = year(curdate())) and (`asignaciones`.`id_mes` <= month(curdate()))))) group by `sucursales`.`idsucursal`,`sucursales`.`sucursal` order by `sucursales`.`sucursal`;

-- ========== view_asignaciones_saldo_pendiente_corregida_en_viaje ==========
CREATE ALGORITHM=UNDEFINED DEFINER=`usernavicat`@`%` SQL SECURITY DEFINER VIEW `view_asignaciones_saldo_pendiente_corregida_en_viaje` AS select `s`.`idsucursal` AS `IdSucursal`,`s`.`sucursal` AS `Sucursal`,coalesce(sum((coalesce(`rm`.`monto`,0) - coalesce(`rp`.`pagos`,0))),0) AS `Saldo` from ((((`sucursales` `s` left join `usuarios` `u` on(((`u`.`idsucursal` = `s`.`idsucursal`) and (`u`.`id_negocio` = 1)))) left join `asignaciones` `a` on(((`a`.`id_asesor` = `u`.`idusuario`) and (`a`.`guardado` = 1) and isnull(`a`.`fec_arribo`) and (`a`.`borrar` = 0) and (`a`.`entregada` = 0) and (`a`.`estado_tasa` = 1) and (`a`.`pagado` = 1) and (`a`.`chasis` is not null) and (`a`.`chasis` <> '') and (not((`a`.`nro_orden` like 'TPA%'))) and ((`a`.`año` < year(curdate())) or ((`a`.`año` = year(curdate())) and (`a`.`id_mes` <= month(curdate()))))))) left join `reservas_suma_montos` `rm` on((`a`.`nro_unidad` = `rm`.`nrounidad`))) left join `reservas_suma_pagos` `rp` on((`a`.`nro_unidad` = `rp`.`nrounidad`))) group by `s`.`idsucursal`,`s`.`sucursal` order by `s`.`sucursal`;

-- ========== view_asignaciones_saldo_pendiente_corregida_llegadas ==========
CREATE ALGORITHM=UNDEFINED DEFINER=`usernavicat`@`%` SQL SECURITY DEFINER VIEW `view_asignaciones_saldo_pendiente_corregida_llegadas` AS select `sucursales`.`idsucursal` AS `IdSucursal`,`sucursales`.`sucursal` AS `Sucursal`,sum((coalesce(`reservas_suma_montos`.`monto`,0) - coalesce(`reservas_suma_pagos`.`pagos`,0))) AS `Saldo`,sum(coalesce(`modelos`.`costo`,0)) AS `Costo`,sum((case when (`asignaciones`.`estado_reserva` = 1) then coalesce(`modelos`.`costo`,0) else 0 end)) AS `CostoConReserva`,sum((case when (`asignaciones`.`estado_reserva` = 1) then 0 else coalesce(`modelos`.`costo`,0) end)) AS `CostoSinReserva`,count(0) AS `Unidades`,sum((case when (`asignaciones`.`estado_reserva` = 1) then 1 else 0 end)) AS `UnidadesConReserva` from (((((`asignaciones` join `usuarios` on((`asignaciones`.`id_asesor` = `usuarios`.`idusuario`))) join `sucursales` on((`usuarios`.`idsucursal` = `sucursales`.`idsucursal`))) join `modelos` on((`asignaciones`.`id_modelo` = `modelos`.`idmodelo`))) left join `reservas_suma_montos` on((`asignaciones`.`nro_unidad` = `reservas_suma_montos`.`nrounidad`))) left join `reservas_suma_pagos` on((`asignaciones`.`nro_unidad` = `reservas_suma_pagos`.`nrounidad`))) where ((`asignaciones`.`guardado` = 1) and (`asignaciones`.`borrar` = 0) and (`asignaciones`.`entregada` = 0) and (`usuarios`.`id_negocio` = 1) and (`asignaciones`.`estado_tasa` = 1) and (`asignaciones`.`pagado` = 1) and (`asignaciones`.`fec_arribo` is not null) and (`asignaciones`.`fec_arribo` <> '') and (not((`asignaciones`.`nro_orden` like 'TPA%'))) and ((`asignaciones`.`año` < year(curdate())) or ((`asignaciones`.`año` = year(curdate())) and (`asignaciones`.`id_mes` <= month(curdate()))))) group by `sucursales`.`idsucursal`,`sucursales`.`sucursal` order by `sucursales`.`sucursal`;

